//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXM
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.BaoHanhs = new HashSet<BaoHanh>();
            this.HoaDonXuats = new HashSet<HoaDonXuat>();
        }
    
        public string MaKH { get; set; }
        public string TenKH { get; set; }
        public string GioiTinh { get; set; }
        public string Diachi { get; set; }
        public string SDT { get; set; }
        public string Ghichu { get; set; }
    
        public virtual ICollection<BaoHanh> BaoHanhs { get; set; }
        public virtual ICollection<HoaDonXuat> HoaDonXuats { get; set; }
    }
}
