//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXM
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.BaoHanhs = new HashSet<BaoHanh>();
            this.HoaDonXuats = new HashSet<HoaDonXuat>();
            this.HoaDonNhaps = new HashSet<HoaDonNhap>();
        }
    
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string Diachi { get; set; }
        public string SDT { get; set; }
        public string ChucVu { get; set; }
        public string CMND { get; set; }
        public Nullable<System.DateTime> Ngayvaolam { get; set; }
        public string Pass { get; set; }
    
        public virtual ICollection<BaoHanh> BaoHanhs { get; set; }
        public virtual ICollection<HoaDonXuat> HoaDonXuats { get; set; }
        public virtual ICollection<HoaDonNhap> HoaDonNhaps { get; set; }
    }
}
