//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXM
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonNhap
    {
        public HoaDonNhap()
        {
            this.ChitietHDNs = new HashSet<ChitietHDN>();
        }
    
        public string MaHDN { get; set; }
        public string MaNV { get; set; }
        public string MaNCC { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
    
        public virtual ICollection<ChitietHDN> ChitietHDNs { get; set; }
        public virtual NCC NCC { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
