//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loaixe
    {
        public Loaixe()
        {
            this.Xes = new HashSet<Xe>();
        }
    
        public string Maloaixe { get; set; }
        public string Tenloaixe { get; set; }
    
        public virtual ICollection<Xe> Xes { get; set; }
    }
}
