//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXM
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCC
    {
        public NCC()
        {
            this.HoaDonNhaps = new HashSet<HoaDonNhap>();
            this.Xes = new HashSet<Xe>();
        }
    
        public string MaNCC { get; set; }
        public string TenNCC { get; set; }
        public string Diachi { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<HoaDonNhap> HoaDonNhaps { get; set; }
        public virtual ICollection<Xe> Xes { get; set; }
    }
}
