//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xe
    {
        public Xe()
        {
            this.BaoHanhs = new HashSet<BaoHanh>();
            this.ChitietHDNs = new HashSet<ChitietHDN>();
            this.ChitietHDXes = new HashSet<ChitietHDX>();
        }
    
        public string MaXe { get; set; }
        public string TenXe { get; set; }
        public string Maloaixe { get; set; }
        public string MaNCC { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
        public string SoKhung { get; set; }
        public string SoMay { get; set; }
        public string Mau { get; set; }
        public string Dungtich { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual ICollection<BaoHanh> BaoHanhs { get; set; }
        public virtual ICollection<ChitietHDN> ChitietHDNs { get; set; }
        public virtual ICollection<ChitietHDX> ChitietHDXes { get; set; }
        public virtual Loaixe Loaixe { get; set; }
        public virtual NCC NCC { get; set; }
    }
}
